spring.application.name=driver-vehicle-service
server.port=8082
spring.data.mongodb.uri=${DRIVER_VEHICLE_MONGODB_URI:mongodb://localhost:27017/ridelink_driver_vehicle}
spring.data.mongodb.auto-index-creation=true
spring.jackson.deserialization.fail-on-unknown-properties=true