spring.application.name=ride-management-service
server.port=8083
spring.data.mongodb.uri=${RIDE_MONGODB_URI:mongodb://localhost:27017/ridelink_ride}
app.services.account.base-url=${ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
app.services.driver-vehicle.base-url=${DRIVER_VEHICLE_SERVICE_BASE_URL:http://localhost:8082}
app.services.connect-timeout=${DOWNSTREAM_CONNECT_TIMEOUT:2s}
app.services.read-timeout=${DOWNSTREAM_READ_TIMEOUT:3s}
